### ISSUE TITLE
Clarify MPI status

### ISSUE THREAD

**Issue by taqtiqa-mark** [justinalsing/dlm#7]
Blocking openjournals/joss-reviews/issues/1157

Either remove the reference to MPI support, or provide instructions and test cases to validate MPI setup.

Relevant discussion [here](https://github.com/openjournals/joss-reviews/issues/1157#issuecomment-477475710).

**Comment by justinalsing** [comment]
I already provide an example script (`dlm_lat_alt_mpi_run.py`) and instructions in the `README` for testing whether the MPI setup works smoothly with the code. 

However, as I've discussed multiple times, the MPI example template is included in the Git repo as a bonus to help MPI users (or at least have MPI installed) get going with MPI runs more quickly. The MPI example template is NOT intended as an integral part of the package itself. I therefore feel that this should not be a blocking issue for JOSS acceptance, and it would seem unfortunate to have to remove it since I believe some people will find it useful (as a bonus). @danielskatz do you want to weight in on this?

**Comment by taqtiqa-mark** [comment]
Understood, but you give no instructions on how to obtain the MPI setup that you say works - I don't doubt you but reproducible research is not waving your hand and saying 'it works for me'.

I'd be happy to close this issue if you just cut the MPI sections out into a separate MPI-README.md with a note to the effect that MPI is not a core part of the package and users are responsible for getting a working MPI+Python stack.

**Comment by justinalsing** [comment]
OK - I've changed the `README` to note that MPI is not supported as a central part of this package, pointing interested users instead to a separate file `MPI-README` for a description of how to get the MPI example template up and running (without going as far to provide full support for getting MPI working smoothly for all users on all OSs). I hope this is satisfactory.

**Comment by danielskatz** [comment]
This seems reasonable to me

@taqtiqa-mark - what do you think?
